###############################################
# Global / system parameters
###############################################
ip: "127.0.0.1"
port: 6009
detect_anomaly: false
quiet: false
seed: 0

###############################################
# ModelParams
###############################################
dataset_path: "./datasets/omni/kitchen_end_start/end"
model_path: "./outputs/omni/kitchen_end_start/base"  
images: "images"

# 语义/特征相关
semantic_features_type: siglip2
semantic_features_dim: 3

###############################################
# OptimizationParams
###############################################
iterations: 5000
